### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by cthomasbabo** [moguchi1/TermProject#2]
1. A technical issue: We may not have covered this is class, but there is more information on the cross origin attribute in this link. [https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin](url) 
Here is a screenshot of the issue from the console tool: 
<img width="948" alt="Screenshot of Technical issue #1" src="https://user-images.githubusercontent.com/98117635/162050376-6cd661fe-601b-4dd6-8da6-a84ee0e1c2df.png">

2. A technical suggestion: I would change element <p> to an unordered list <ul> on the practicing Japanese sentences page. This will make the hints easier to style in CSS. 
Here is a screenshot of the code I'm referencing: 
<img width="326" alt="Screenshot of Technical issue #2 1" src="https://user-images.githubusercontent.com/98117635/162050730-d9ce0814-4ef1-41f7-b929-0a57ca2973ee.png">

Content Suggestions
1. You can add a page of content with video & audio conversations in Japanese and the history of the language! 
2. Maybe create a color scheme that represents Japanese culture for the website and that will also eliminate most of the white space. You could also embed some cool fonts to make the website more aesthetically appealing. 

Your website is really great overall! It is rich with content and the layout is easy to read and navigate. Very user friendly and super impressive! Great work!!

**Comment by moguchi1** [comment]
Thank you so much for looking at my website and spending time!! I really appreciate your suggestions. I fixed the errors on console. I used your second suggestion of color scheme too! Thank you.
