### ISSUE TITLE
Technical Issue: Remove link decoration

### ISSUE THREAD

**Issue by tomasgarcia3** [moguchi1/TermProject#3]
https://github.com/moguchi1/TermProject/blob/ac9e4848ecbf7422ba03871fdbf4294b2efc6336/index.html#L93-L107

I would recommend removing the text decoration in the links you have in the nav bar. This would make it much cleaner especially since you already have a hover feature when moving from a page to a page. For more information about styling links with CSS I am adding a link to a W3schools page. 

https://www.w3schools.com/css/css_link.asp

**Comment by moguchi1** [comment]
Thank you for looking at my website and spending time! I fixed it!
