### ISSUE TITLE
Technical Suggestion 2: Add email HTML tag

### ISSUE THREAD

**Issue by tomasgarcia3** [moguchi1/TermProject#4]
https://github.com/moguchi1/TermProject/blob/ac9e4848ecbf7422ba03871fdbf4294b2efc6336/contact.html#L124

I think if you are putting your contact email it would be a good idea to add an HTML email tag so that when the email si clicked someone can contact you without having to go to their email and write your email down. Is a nice feature to implement.

**Comment by moguchi1** [comment]
That is so true. I work on that!
