### ISSUE TITLE
Content Idea 2: Japan culture content

### ISSUE THREAD

**Issue by tomasgarcia3** [moguchi1/TermProject#6]
Since the website is also about tips when visiting Japan I think you should talk more about the culture. Things like food, interest, behavior, and even compare to other cultures like the US. Here people could learn more about things they would probably encounter when visiting and maybe understand more about the places they are visiting.

**Comment by moguchi1** [comment]
Instead, i mostly focused on Japanese language and my university! Thanks for suggestions!
